const processes=[
 {id:'preboarding',name:'Пребординг',result:'Готовность к первому рабочему дню',event:'ATS · оффер принят',stats:['6 этапов','3 ветки','47 действий'],updated:'Сегодня, 20:42',status:'published'},
 {id:'onboarding',name:'Новый сотрудник · адаптация',result:'Выход на целевую продуктивность',event:'Мастер-система · сотрудник вышел',stats:['8 этапов','3 ветки','47 действий'],updated:'Сегодня, 21:36',status:'published'},
 {id:'transfer',name:'Внутренний переход',result:'Готовность к новой должности',event:'Мастер-система · должность изменилась',stats:['7 этапов','3 ветки','47 действий'],updated:'Вчера, 18:10',status:'published'},
 {id:'learning',name:'Программа обучения',result:'Пробел навыка закрыт и подтверждён',event:'Оценка / расписание / ручной запуск',stats:['7 этапов','3 ветки','47 действий'],updated:'Вчера, 16:24',status:'draft'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function render(){const q=$('#search').value.toLowerCase(),st=$('#status').value;const rows=processes.filter(p=>(p.name+p.result+p.event).toLowerCase().includes(q)&&(st==='all'||p.status===st));$('#count').textContent=`${rows.length} процесса`;$('#processList').innerHTML=rows.map(p=>`<a class="process-row" href="workflow.html?process=${p.id}"><div><h2>${p.name}</h2><p>${p.result}</p><div class="meta">${p.stats.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="cell"><small>Событие запуска</small><b>${p.event}</b></div><div class="cell"><small>Логика</small><b>Общая часть + ветки</b><small>Результаты меняют маршрут</small></div><div class="cell"><small>Изменён</small><b>${p.updated}</b><span class="status ${p.status==='draft'?'draft':''}">${p.status==='draft'?'Черновик':'Опубликован'}</span></div><span class="open">Открыть →</span></a>`).join('')||'<div class="value">Процессы не найдены</div>'}
$('#search').oninput=render;$('#status').onchange=render;
let step=1,ai=false;function openWizard(withAi){ai=withAi;step=1;$('#wizardTag').textContent=ai?'AI · черновик под контролем':'Новый процесс';$('#wizardTitle').textContent=ai?'Задайте рамки — AI соберёт черновик':'Настройте рамки процесса';$('#aiNote').style.display=ai?'block':'none';sync();$('#wizard').classList.add('open');}
function sync(){$$('.step').forEach(x=>x.classList.toggle('hidden',+x.dataset.step!==step));$$('[data-step-nav]').forEach(x=>x.classList.toggle('active',+x.dataset.stepNav===step));$('#next').textContent=step===4?(ai?'Создать черновик с AI':'Перейти к процессу'):'Продолжить';}
$('#createAi').onclick=()=>openWizard(true);$('#createManual').onclick=()=>openWizard(false);$$('[data-close]').forEach(x=>x.onclick=()=>$('#wizard').classList.remove('open'));$$('[data-step-nav]').forEach(x=>x.onclick=()=>{step=+x.dataset.stepNav;sync()});$('#next').onclick=()=>{if(step<4){step++;sync()}else{const name=encodeURIComponent($('#newName').value||'Новый процесс'),result=encodeURIComponent($('#newResult').value||'Целевой результат'),event=encodeURIComponent($('#newEvent').value);location.href=`workflow.html?process=${ai?'aiDraft':'draft'}&name=${name}&result=${result}&event=${event}`}};render();if(location.hash==='#new')openWizard(false);
