const baseProcesses=[
 {id:'preboarding',name:'Пребординг',result:'Готовность к первому рабочему дню',event:'ATS · оффер принят',stats:['6 этапов','3 ветки','47 действий'],updated:'Сегодня, 20:42',status:'published'},
 {id:'onboarding',name:'Новый сотрудник · адаптация',result:'Выход на целевую продуктивность',event:'Мастер-система · сотрудник вышел',stats:['8 этапов','3 ветки','47 действий'],updated:'Сегодня, 21:36',status:'published'},
 {id:'transfer',name:'Внутренний переход',result:'Готовность к новой должности',event:'Мастер-система · должность изменилась',stats:['7 этапов','3 ветки','47 действий'],updated:'Вчера, 18:10',status:'published'},
 {id:'learning',name:'Программа обучения',result:'Пробел навыка закрыт и подтверждён',event:'Оценка / расписание / ручной запуск',stats:['7 этапов','3 ветки','47 действий'],updated:'Вчера, 16:24',status:'draft'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const getProcesses=()=>[...(window.SkillazDemoDB?.loadProcesses()||[]),...baseProcesses];
function render(){const q=$('#search').value.toLowerCase(),st=$('#status').value;const rows=getProcesses().filter(p=>(p.name+p.result+p.event).toLowerCase().includes(q)&&(st==='all'||p.status===st));$('#count').textContent=`${rows.length} процессов`;$('#processList').innerHTML=rows.map(p=>`<article class="process-row"><div><h2>${p.name}</h2><p>${p.result}</p><div class="meta">${p.stats.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="cell"><small>Событие запуска</small><b>${p.event}</b></div><div class="cell"><small>Логика</small><b>Общая часть + ветки</b><small>Результаты меняют маршрут</small></div><div class="cell"><small>Изменён</small><b>${p.updated}</b><span class="status ${p.status==='draft'?'draft':''}">${p.status==='draft'?'Черновик':'Опубликован'}</span></div><div class="row-actions"><a class="open" href="${p.href||`workflow.html?process=${p.id}`}">Открыть →</a>${p.id.startsWith('custom-')?`<button class="delete-process" data-delete="${p.id}" title="Удалить тестовый процесс">Удалить</button>`:''}</div></article>`).join('')||'<div class="value">Процессы не найдены</div>';$$('[data-delete]').forEach(button=>button.onclick=()=>{if(confirm('Удалить тестовый процесс и сохранённую схему?')){window.SkillazDemoDB?.deleteProcess(button.dataset.delete);render()}})}
$('#search').oninput=render;$('#status').onchange=render;
const eventSelect=$('#newEvent');if(window.SkillazDemoDB){eventSelect.innerHTML=window.SkillazDemoDB.events.map(([id,name])=>`<option value="${name}">${name}</option>`).join('')}
let step=1,ai=false;function openWizard(withAi){ai=withAi;step=1;$('#wizardTag').textContent=ai?'AI · черновик под контролем':'Новый процесс';$('#wizardTitle').textContent=ai?'Задайте рамки — AI соберёт черновик':'Настройте рамки процесса';$('#aiNote').style.display=ai?'block':'none';sync();$('#wizard').classList.add('open');}
function sync(){$$('.step').forEach(x=>x.classList.toggle('hidden',+x.dataset.step!==step));$$('[data-step-nav]').forEach(x=>x.classList.toggle('active',+x.dataset.stepNav===step));$('#next').textContent=step===4?(ai?'Создать черновик с AI':'Перейти к процессу'):'Продолжить';}
$('#createAi').onclick=()=>openWizard(true);$('#createManual').onclick=()=>openWizard(false);$$('[data-close]').forEach(x=>x.onclick=()=>$('#wizard').classList.remove('open'));$$('[data-step-nav]').forEach(x=>x.onclick=()=>{step=+x.dataset.stepNav;sync()});
$('#next').onclick=()=>{if(step<4){step++;sync();return}const rawName=$('#newName').value||'Новый процесс',rawResult=$('#newResult').value||'Целевой результат',rawEvent=$('#newEvent').value,id='custom-'+Date.now(),processType=ai?'aiDraft':'draft',href=`workflow.html?process=${processType}&customId=${id}&name=${encodeURIComponent(rawName)}&result=${encodeURIComponent(rawResult)}&event=${encodeURIComponent(rawEvent)}`;window.SkillazDemoDB?.saveProcess({id,name:rawName,result:rawResult,event:rawEvent,stats:[ai?'AI черновик':'Пустой процесс','3 ветки','0 действий'],updated:'Только что',status:'draft',href});location.href=href};
render();if(location.hash==='#new')openWizard(false);
