const C={start:'#20a878',end:'#2f69e8',task:'#2f69e8',course:'#7357d9',article:'#2a8e79',goal:'#9c5a11',checkpoint:'#e07535',decision:'#7399e0',test:'#cc5b52',meeting:'#1680a6',survey:'#526b80'};
const typeName={start:'Событие',end:'Результат',task:'Задача',course:'Курс / программа',article:'Статья / файл',goal:'Цель',checkpoint:'Контрольная точка',decision:'Условие',test:'Тест',meeting:'Встреча',survey:'Опрос'};
const icon={start:'⚡',end:'✓',task:'✓',course:'▣',article:'≡',goal:'◎',checkpoint:'◆',decision:'◇',test:'☑',meeting:'◷',survey:'◉'};
const catalogs={
  course:[['crs-101','Стандарты клиентского сервиса','Курс · 45 мин'],['crs-102','СДЭК — как это работает','Онлайн-курс · 50 мин'],['crs-103','Охрана труда и безопасность','Обязательный курс · 35 мин'],['crs-104','Работа в WMS и со сканером','Практический курс · 60 мин'],['crs-105','Эффективная подготовка к переговорам','Онлайн-курс · 40 мин'],['crs-106','Установление контакта','Онлайн-курс · 35 мин'],['crs-107','Работа с потребностью клиента','Онлайн-курс · 55 мин'],['crs-108','Работа с возражениями','Онлайн-курс · 45 мин'],['crs-109','Роль руководителя и лидерство','Программа · 8 модулей'],['crs-110','SMART цели и регулярный менеджмент','Курс · 70 мин']],
  article:[['kb-801','Что будет в первый рабочий день','База знаний LMS'],['kb-802','Корпоративные ресурсы компании','База знаний LMS'],['kb-803','Регламент и обязательные требования','База знаний LMS'],['kb-804','Продукты, услуги и клиентский путь','База знаний LMS'],['kb-805','Документы и правила передачи отправления','База знаний LMS']],
  test:[['tst-301','Проверка стандартов общения','Тест · порог 80%'],['tst-302','Входная диагностика навыка','Тест · 30 вопросов'],['tst-303','Проверка работы в приложении','Тест · порог 85%'],['tst-304','Проверка знаний обязательной программы','Тест · 2 попытки']],
  survey:[['srv-201','Пульс первого дня','Опрос · 5 вопросов'],['srv-202','Пульс адаптации 30 дней','Опрос · 9 вопросов'],['srv-203','Обратная связь по обучению','Опрос · 7 вопросов'],['srv-204','Обратная связь 360','Оценка · 6 групп']],
  task:[['tsk-401','Наблюдение за работой наставника','Шаблон задачи сотруднику'],['tsk-402','Самостоятельная рабочая практика','Шаблон задачи сотруднику'],['tsk-403','Разбор ошибок и обратная связь','Шаблон задачи наставнику'],['tsk-404','Подтвердить готовность доступов','Шаблон задачи IT / HR'],['tsk-405','Контрольная встреча 30 дней','Шаблон задачи руководителю']],
  goal:[['gol-101','Создать цели адаптации','Сценарий: сотрудник создаёт цель'],['gol-102','Согласовать цели новой роли','Сценарий: сотрудник + руководитель'],['gol-103','Цель развития навыка','Сценарий: сотрудник создаёт цель']],
  checkpoint:[['kt-101','Готовность к первому рабочему дню','Лист проверки · HR'],['kt-102','Практический навык подтверждён','Лист оценки · эксперт'],['kt-103','Контрольная точка 30 дней','Лист проверки · руководитель'],['kt-104','Итоговая аттестация','Лист оценки · комиссия ролей']],
  meeting:[['mtg-101','Встреча с наставником','Шаблон встречи'],['mtg-102','Контрольная встреча с руководителем','Шаблон встречи'],['mtg-103','Разбор практического кейса','Шаблон встречи']],
  decision:[['rul-101','Результат теста достиг порога?','Условие по результату'],['rul-102','Практический навык подтверждён?','Условие по листу оценки'],['rul-103','Есть риск срока или ухода?','Вычисляемое условие'],['rul-104','Цель достигнута раньше срока?','Условие по статусу цели'],['rul-105','К какой группе относится сотрудник?','Условие по данным мастер-системы']]
};
const catalogNames={course:'Курсы и программы',article:'База знаний LMS',test:'Тесты',survey:'Опросы и оценки',task:'Шаблоны задач',goal:'Сценарии целей',checkpoint:'Листы проверки',meeting:'Шаблоны встреч',decision:'Справочник условий'};
const N=(id,type,title,x,y,owner='Сотрудник',branch='common',extra={})=>({id,type,title,x,y,owner,branch,time:extra.time||'С открытием этапа',notification:extra.notification||'Напомнить за 1 день',outcomes:extra.outcomes||['success','fail'],note:extra.note||''});
const E=(from,to,label='',branch='common',outcome='any',tone='')=>({from,to,label,branch,outcome,tone});

const processes={
  onboarding:{title:'Адаптация нового сотрудника',result:'Выход на целевую продуктивность',meta:'7 этапов · 3 ветки · 22 элемента',branches:[['client','Клиентский офис'],['warehouse','Склад'],['delivery','Доставка']],frames:[
    {id:'client',title:'Клиентский офис',condition:'Подразделение: клиентские офисы',x:735,y:45,w:880,h:275,color:'#e6f7f1'},
    {id:'warehouse',title:'Склад',condition:'Подразделение: склад',x:735,y:350,w:880,h:275,color:'#fff2d8'},
    {id:'delivery',title:'Доставка',condition:'Должность: курьер',x:735,y:655,w:880,h:275,color:'#eeeaff'}],nodes:[
      N('s','start','Сотрудник вышел',60,440,'Система'),N('access','task','Подтвердить готовность доступов',260,250,'Сотрудник'),N('welcome','course','Добро пожаловать в компанию',260,420),N('goals','goal','Согласовать цели адаптации',260,590,'Руководитель'),N('d','decision','Какая рабочая роль?',555,435,'Система'),
      N('c1','course','Стандарты клиентского сервиса',780,105,'Сотрудник','client'),N('c2','task','Провести диалог под наблюдением',1055,105,'Сотрудник','client'),N('c3','test','Проверка стандартов общения',1330,105,'Сотрудник','client'),N('cfix','task','Разобрать ошибки диалога',1055,205,'Наставник','client',{outcomes:['fail']}),
      N('w1','course','Охрана труда и складские операции',780,410,'Сотрудник','warehouse'),N('w2','task','Выполнить смену с наставником',1055,410,'Сотрудник','warehouse'),N('w3','checkpoint','Подтвердить практический навык',1330,410,'Проверяющий','warehouse'),N('wfix','course','Повторить безопасную операцию',1055,510,'Сотрудник','warehouse',{outcomes:['fail']}),
      N('d1','course','Маршрут, приложение и стандарты доставки',780,715,'Сотрудник','delivery'),N('d2','task','Выполнить первый маршрут',1055,715,'Сотрудник','delivery'),N('d3','test','Проверка работы в приложении',1330,715,'Сотрудник','delivery'),N('dfix','meeting','Разбор маршрута с наставником',1055,815,'Наставник','delivery',{outcomes:['fail']}),
      N('kt','checkpoint','Контрольная встреча 30 дней',1665,430,'Руководитель'),N('self','survey','Пульс адаптации',1885,300),N('ipr','goal','Зафиксировать цели развития',1885,480,'Сотрудник'),N('risk','task','Согласовать корректирующий план',1885,660,'Руководитель','common',{outcomes:['fail']}),N('end','end','Готов к самостоятельной работе',2180,445,'Система')],edges:[
      E('s','access'),E('access','welcome'),E('welcome','goals'),E('goals','d','Определить ветку'),E('d','c1','Клиентский офис','client'),E('d','w1','Склад','warehouse'),E('d','d1','Доставка','delivery'),
      E('c1','c2'),E('c2','c3'),E('c3','kt','Тест ≥ 80%','client','success','positive'),E('c3','cfix','Тест < 80%','client','fail','negative'),E('cfix','c2','После разбора','client','fail'),
      E('w1','w2'),E('w2','w3'),E('w3','kt','Навык подтверждён','warehouse','success','positive'),E('w3','wfix','Нужна практика','warehouse','fail','negative'),E('wfix','w2','Повторить смену','warehouse','fail'),
      E('d1','d2'),E('d2','d3'),E('d3','kt','Тест пройден','delivery','success','positive'),E('d3','dfix','Есть ошибки','delivery','fail','negative'),E('dfix','d2','Новый маршрут','delivery','fail'),
      E('kt','self'),E('kt','ipr'),E('kt','risk','Есть риск','common','fail','negative'),E('self','end'),E('ipr','end'),E('risk','kt','После коррекции','common','fail') ]},

  preboarding:{title:'Пребординг',result:'Готовность к первому рабочему дню',meta:'6 этапов · 3 ветки · 22 элемента',branches:[['office','Офис'],['remote','Удалённо'],['field','Разъездная работа']],frames:[
    {id:'office',title:'Офис',condition:'Формат работы: офис',x:720,y:45,w:900,h:275,color:'#e6f7f1'},
    {id:'remote',title:'Удалённо',condition:'Формат работы: удалённо',x:720,y:350,w:900,h:275,color:'#e8f0ff'},
    {id:'field',title:'Разъездная работа',condition:'Должность: курьер / полевой сотрудник',x:720,y:655,w:900,h:275,color:'#fff2d8'}],nodes:[
      N('s','start','Оффер принят',55,440,'ATS'),N('docs','task','Заполнить данные и документы',250,250),N('hr','task','Проверить документы',250,430,'HR'),N('intro','article','Что будет в первый рабочий день',250,610),N('d','decision','Как сотрудник будет работать?',535,435,'Система'),
      N('o1','task','Создать пропуск и доступы',765,105,'HR / IT','office'),N('o2','task','Подготовить рабочее место',1045,105,'Офис-менеджер','office'),N('o3','meeting','Назначить buddy и встречу',1325,105,'Руководитель','office'),N('ofix','task','Эскалировать неготовый доступ',1045,205,'HR','office',{outcomes:['fail']}),
      N('r1','task','Отправить комплект оборудования',765,410,'IT / логистика','remote'),N('r2','task','Проверить VPN и учётную запись',1045,410,'Сотрудник','remote'),N('r3','meeting','Провести вводный созвон',1325,410,'Руководитель','remote'),N('rfix','task','Повторно настроить доступ',1045,510,'IT','remote',{outcomes:['fail']}),
      N('f1','course','Безопасность и стандарты работы',765,715,'Сотрудник','field'),N('f2','task','Выдать устройство и форму',1045,715,'HR / логистика','field'),N('f3','meeting','Связаться с наставником',1325,715,'Наставник','field'),N('ffix','task','Закрыть блокер комплектации',1045,815,'HR','field',{outcomes:['fail']}),
      N('ready','checkpoint','Готовность к выходу',1665,430,'HR'),N('welcome','article','Памятка первого дня',1880,280),N('manager','task','Подготовить план первой недели',1880,455,'Руководитель'),N('block','task','Разобрать блокер до выхода',1880,640,'HR','common',{outcomes:['fail']}),N('end','end','Первый день подтверждён',2170,445,'Система')],edges:[
      E('s','docs'),E('docs','hr'),E('hr','intro'),E('intro','d'),E('d','o1','Офис','office'),E('d','r1','Удалённо','remote'),E('d','f1','Разъездной формат','field'),
      E('o1','o2'),E('o2','o3'),E('o3','ready','Всё готово','office','success','positive'),E('o2','ofix','Доступ не готов','office','fail','negative'),E('ofix','o2','Исправлено','office','fail'),
      E('r1','r2'),E('r2','r3'),E('r3','ready','Связь проверена','remote','success','positive'),E('r2','rfix','Нет доступа','remote','fail','negative'),E('rfix','r2','Повторная проверка','remote','fail'),
      E('f1','f2'),E('f2','f3'),E('f3','ready','Комплект получен','field','success','positive'),E('f2','ffix','Не хватает комплекта','field','fail','negative'),E('ffix','f2','Доукомплектовано','field','fail'),
      E('ready','welcome'),E('ready','manager'),E('ready','block','Есть блокер','common','fail','negative'),E('welcome','end'),E('manager','end'),E('block','ready','Перепроверить','common','fail') ]},

  transfer:{title:'Внутренний переход',result:'Готовность к новой роли',meta:'7 этапов · 3 ветки · 22 элемента',branches:[['expert','Экспертная роль'],['manager','Руководитель'],['career','Смена карьерного направления']],frames:[
    {id:'expert',title:'Экспертная роль',condition:'Тип перехода: рост экспертизы',x:720,y:45,w:900,h:275,color:'#e6f7f1'},
    {id:'manager',title:'Руководитель',condition:'Новая роль управляет командой',x:720,y:350,w:900,h:275,color:'#eeeaff'},
    {id:'career',title:'Смена направления',condition:'Семейство должностей изменилось',x:720,y:655,w:900,h:275,color:'#fff2d8'}],nodes:[
      N('s','start','Должность изменилась',55,440,'Мастер-система'),N('profile','checkpoint','Сопоставить навыки новой роли',250,245,'Система'),N('meeting','meeting','Обсудить ожидания и зону ответственности',250,430,'Руководитель'),N('goal','goal','Создать и согласовать цели перехода',250,615,'Сотрудник'),N('d','decision','Какой тип перехода?',535,435,'Система'),
      N('e1','course','Освоить обязательную экспертизу',765,105,'Сотрудник','expert'),N('e2','task','Выполнить рабочий кейс',1045,105,'Сотрудник','expert'),N('e3','checkpoint','Защитить кейс у эксперта',1325,105,'Эксперт','expert'),N('efix','course','Закрыть выявленный пробел',1045,205,'Сотрудник','expert',{outcomes:['fail']}),
      N('m1','course','Основы управления командой',765,410,'Сотрудник','manager'),N('m2','goal','Сформировать цели команды',1045,410,'Руководитель','manager'),N('m3','meeting','Провести первую встречу 1:1',1325,410,'Руководитель','manager'),N('mfix','task','Подготовить план поддержки',1045,510,'HRBP','manager',{outcomes:['fail']}),
      N('c1','checkpoint','Оценить переносимые навыки',765,715,'Руководитель','career'),N('c2','goal','Собрать ИПР под новую роль',1045,715,'Сотрудник','career'),N('c3','task','Пройти практику в новой функции',1325,715,'Сотрудник','career'),N('cfix','course','Добавить базовый модуль в ИПР',1045,815,'Сотрудник','career',{outcomes:['fail']}),
      N('kt','checkpoint','КТ готовности 30 дней',1665,430,'Руководитель'),N('feedback','survey','Получить обратную связь 360',1880,275),N('confirm','task','Подтвердить цели на период',1880,450,'Руководитель'),N('correct','task','Скорректировать ИПР и сроки',1880,635,'Сотрудник','common',{outcomes:['fail']}),N('end','end','Самостоятельно работает в новой роли',2180,445,'Система')],edges:[
      E('s','profile'),E('profile','meeting'),E('meeting','goal'),E('goal','d'),E('d','e1','Эксперт','expert'),E('d','m1','Руководитель','manager'),E('d','c1','Смена направления','career'),
      E('e1','e2'),E('e2','e3'),E('e3','kt','Кейс защищён','expert','success','positive'),E('e3','efix','Есть пробел','expert','fail','negative'),E('efix','e2','Новая попытка','expert','fail'),
      E('m1','m2'),E('m2','m3'),E('m3','kt','Практика подтверждена','manager','success','positive'),E('m3','mfix','Нужна поддержка','manager','fail','negative'),E('mfix','m3','После поддержки','manager','fail'),
      E('c1','c2'),E('c2','c3'),E('c3','kt','Практика завершена','career','success','positive'),E('c1','cfix','Базовых навыков нет','career','fail','negative'),E('cfix','c2','Навыки добавлены','career','fail'),
      E('kt','feedback'),E('kt','confirm'),E('kt','correct','Роль не освоена','common','fail','negative'),E('feedback','end'),E('confirm','end'),E('correct','kt','Повторная КТ','common','fail') ]},

  learning:{title:'Программа обучения',result:'Пробел навыка закрыт',meta:'6 этапов · 3 ветки · 22 элемента',branches:[['gap','По результатам оценки'],['mandatory','Обязательное обучение'],['request','По запросу развития']],frames:[
    {id:'gap',title:'Пробел навыка',condition:'Оценка ниже целевого уровня',x:720,y:45,w:900,h:275,color:'#e8f0ff'},
    {id:'mandatory',title:'Обязательная программа',condition:'Должность требует допуска',x:720,y:350,w:900,h:275,color:'#fff2d8'},
    {id:'request',title:'Индивидуальный запрос',condition:'Сотрудник или руководитель инициировал',x:720,y:655,w:900,h:275,color:'#e6f7f1'}],nodes:[
      N('s','start','Потребность в обучении найдена',55,440,'Оценка / руководитель'),N('profile','checkpoint','Определить целевой навык и уровень',250,245,'Система'),N('approve','task','Подтвердить цель обучения',250,430,'Руководитель'),N('goal','goal','Создать цель развития',250,615,'Сотрудник'),N('d','decision','Почему назначено обучение?',535,435,'Система'),
      N('g1','course','Персональная подборка по пробелу',765,105,'Сотрудник','gap'),N('g2','task','Применить навык в рабочем кейсе',1045,105,'Сотрудник','gap'),N('g3','test','Повторная оценка навыка',1325,105,'Сотрудник','gap'),N('gfix','course','Добавить материал по ошибкам',1045,205,'Сотрудник','gap',{outcomes:['fail']}),
      N('m1','course','Обязательная программа и регламент',765,410,'Сотрудник','mandatory'),N('m2','test','Проверка знаний',1045,410,'Сотрудник','mandatory'),N('m3','checkpoint','Оформить допуск',1325,410,'Ответственный','mandatory'),N('mfix','course','Повторить обязательный модуль',1045,510,'Сотрудник','mandatory',{outcomes:['fail']}),
      N('r1','article','Подборка статей и видео',765,715,'Сотрудник','request'),N('r2','course','Курс по выбранной теме',1045,715,'Сотрудник','request'),N('r3','meeting','Обсудить применение с руководителем',1325,715,'Руководитель','request'),N('rfix','task','Уточнить цель и выбрать другой материал',1045,815,'Сотрудник','request',{outcomes:['fail']}),
      N('kt','checkpoint','Проверка результата обучения',1665,430,'Руководитель'),N('practice','task','Зафиксировать применение навыка',1880,275,'Сотрудник'),N('feedback','survey','Оценить полезность программы',1880,450),N('correct','task','Продлить маршрут и назначить практику',1880,635,'Руководитель','common',{outcomes:['fail']}),N('end','end','Целевой уровень навыка достигнут',2180,445,'Система')],edges:[
      E('s','profile'),E('profile','approve'),E('approve','goal'),E('goal','d'),E('d','g1','Есть пробел','gap'),E('d','m1','Нужен допуск','mandatory'),E('d','r1','Запрос развития','request'),
      E('g1','g2'),E('g2','g3'),E('g3','kt','Оценка ≥ цели','gap','success','positive'),E('g3','gfix','Оценка ниже цели','gap','fail','negative'),E('gfix','g2','Новый кейс','gap','fail'),
      E('m1','m2'),E('m2','m3','Тест ≥ 80%','mandatory','success','positive'),E('m2','mfix','Тест < 80%','mandatory','fail','negative'),E('mfix','m2','Повторный тест','mandatory','fail'),E('m3','kt'),
      E('r1','r2'),E('r2','r3'),E('r3','kt','Цель подтверждена','request','success','positive'),E('r3','rfix','Не отвечает цели','request','fail','negative'),E('rfix','r2','Новая подборка','request','fail'),
      E('kt','practice'),E('kt','feedback'),E('kt','correct','Результата нет','common','fail','negative'),E('practice','end'),E('feedback','end'),E('correct','kt','После практики','common','fail') ]}
};

// Боевые демонстрационные процессы: плотность и типы действий основаны на
// реальных редакторах программ и планов, а данные сотрудников не используются.
function buildRich(cfg){
  const ys=[20,500,980],colors=['#e6f7f1','#fff2d8','#eeeaff'];
  const frames=cfg.branches.map((b,i)=>({id:b.id,title:b.name,condition:b.condition,x:1240,y:ys[i],w:2820,h:420,color:colors[i]}));
  const nodes=[N('s','start',cfg.start,60,690,cfg.source),
    N('base1',cfg.common[0][0],cfg.common[0][1],260,690,cfg.common[0][2]),
    N('base2',cfg.common[1][0],cfg.common[1][1],510,690,cfg.common[1][2]),
    N('base3',cfg.common[2][0],cfg.common[2][1],760,690,cfg.common[2][2]),
    N('base4',cfg.common[3][0],cfg.common[3][1],1010,690,cfg.common[3][2]),
    N('d','decision',cfg.decision,1045,520,'Система')];
  const edges=[E('s','base1'),E('base1','base2'),E('base2','base3'),E('base3','base4'),E('base4','d','Определить ветку')];
  cfg.branches.forEach((b,i)=>{
    const y=ys[i],mainY=y+78,fixY=y+250,xs=Array.from({length:10},(_,j)=>1290+j*270);
    const main=[...b.items.slice(0,6),['meeting',`Промежуточный разбор: ${b.name}`,'Наставник'],['task',`Самостоятельная практика: ${b.name}`,'Сотрудник'],['survey',`Обратная связь по этапу: ${b.name}`,'Сотрудник'],['checkpoint',`Итоговая проверка: ${b.name}`,'Руководитель']];
    main.forEach((it,j)=>nodes.push(N(`${b.id}${j+1}`,it[0],it[1],xs[j],mainY,it[2],b.id,{notification:it[3]||'Назначение + напоминание'})));
    nodes.push(N(`${b.id}fix1`,b.items[6][0],b.items[6][1],2100,fixY,b.items[6][2],b.id,{outcomes:['fail'],notification:'Результат требует внимания'}));
    nodes.push(N(`${b.id}fix2`,b.items[7][0],b.items[7][1],3180,fixY,b.items[7][2],b.id,{outcomes:['fail'],notification:'Эскалация руководителю'}));
    edges.push(E('d',`${b.id}1`,b.name,b.id));
    for(let j=1;j<10;j++)edges.push(E(`${b.id}${j}`,`${b.id}${j+1}`,'',b.id));
    edges.push(E(`${b.id}4`,`${b.id}fix1`,b.fail1||'Результат ниже порога',b.id,'fail','negative'),E(`${b.id}fix1`,`${b.id}4`,'После доработки',b.id,'fail'));
    edges.push(E(`${b.id}8`,`${b.id}fix2`,b.fail2||'Есть риск',b.id,'fail','negative'),E(`${b.id}fix2`,`${b.id}8`,'Повторная проверка',b.id,'fail'));
    edges.push(E(`${b.id}10`,'kt',b.success||'Критерии выполнены',b.id,'success','positive'));
  });
  nodes.push(N('kt','checkpoint',cfg.checkpoint,4210,690,cfg.checkOwner),
    N('post1',cfg.post[0][0],cfg.post[0][1],4460,470,cfg.post[0][2]),
    N('post2',cfg.post[1][0],cfg.post[1][1],4460,690,cfg.post[1][2]),
    N('risk',cfg.post[2][0],cfg.post[2][1],4460,910,cfg.post[2][2],'common',{outcomes:['fail'],notification:'Эскалация и подключение ответственного'}),
    N('end','end',cfg.end,4790,690,'Система'));
  edges.push(E('kt','post1','Результат подтверждён','common','success','positive'),E('kt','post2','Следующий шаг','common','success','positive'),E('kt','risk','КТ не пройдена / есть риск','common','fail','negative'),E('post1','end'),E('post2','end'),E('risk','kt','После коррекции','common','fail'));
  return {title:cfg.title,result:cfg.result,event:cfg.event,meta:`${cfg.stages} этапов · 3 ветки · ${nodes.length} действий`,branches:cfg.branches.map(b=>[b.id,b.name]),frames,nodes,edges};
}

processes.preboarding=buildRich({title:'Пребординг',result:'Готовность к первому рабочему дню',event:'ATS · оффер принят',stages:6,start:'Оффер принят',source:'ATS',decision:'Как сотрудник будет работать?',common:[
  ['task','Заполнить персональные данные и документы','Сотрудник'],['task','Проверить документы и дату выхода','HR'],['article','Памятка до первого рабочего дня','Сотрудник'],['task','Назначить руководителя и наставника','HR']],checkpoint:'Контроль готовности за 2 дня',checkOwner:'HR',post:[['article','Отправить программу первого дня','Сотрудник'],['task','Руководителю подтвердить план первой недели','Руководитель'],['task','Закрыть блокер или перенести дату выхода','HR']],end:'Готов к первому рабочему дню',branches:[
  {id:'office',name:'Офис',condition:'Формат работы = офис',success:'Все ресурсы готовы',items:[['task','Создать учётную запись и почту','IT'],['task','Оформить пропуск','HR'],['task','Подготовить рабочее место','Офис-менеджер'],['article','Схема офиса и контакты команды','Сотрудник'],['meeting','Назначить встречу с командой','Руководитель'],['task','Подтвердить готовность первого дня','Сотрудник'],['task','Эскалировать неготовые доступы','IT'],['task','Доукомплектовать рабочее место','Офис-менеджер']]},
  {id:'remote',name:'Удалённо',condition:'Формат работы = удалённо',success:'Связь и оборудование проверены',items:[['task','Подтвердить адрес доставки','Сотрудник'],['task','Отправить комплект оборудования','Логистика'],['task','Подписать документы электронно','Сотрудник'],['task','Настроить VPN и MFA','IT'],['meeting','Провести тестовый созвон','Руководитель'],['course','Пройти инструктаж по ИБ','Сотрудник'],['task','Повторно настроить доступ','IT'],['task','Эскалировать задержку доставки','HR']]},
  {id:'field',name:'Разъездная работа',condition:'Должность = курьер / полевой сотрудник',success:'Комплект и допуски получены',items:[['task','Проверить обязательные документы','HR'],['course','Охрана труда и безопасность','Сотрудник'],['task','Выдать форму и устройство','Логистика'],['course','Работа в мобильном приложении','Сотрудник'],['meeting','Назначить наставника и первую смену','Руководитель'],['task','Подтвердить место и время старта','Сотрудник'],['course','Повторить обязательный инструктаж','Сотрудник'],['task','Закрыть блокер комплектации','Логистика']]}
]});

processes.onboarding=buildRich({title:'Новый сотрудник · адаптация',result:'Выход на целевую продуктивность',event:'Мастер-система · сотрудник вышел',stages:8,start:'Сотрудник вышел',source:'Мастер-система',decision:'Какая рабочая роль?',common:[
  ['article','Привет, коллега: компания и ресурсы','Сотрудник'],['task','Подтвердить готовность доступов','Сотрудник'],['goal','Сотруднику создать цели адаптации','Сотрудник'],['meeting','Руководителю согласовать цели и план 90 дней','Руководитель']],checkpoint:'Контрольная встреча 30 дней',checkOwner:'Руководитель',post:[['survey','Пульс адаптации и обратная связь','Сотрудник'],['goal','Подтвердить цели на следующие 60 дней','Руководитель'],['task','Собрать корректирующий план и практику','Руководитель']],end:'Самостоятельно работает по стандартам',branches:[
  {id:'client',name:'Клиентский офис',condition:'Подразделение = клиентские офисы',success:'Тест ≥ 80% и практика принята',items:[['course','Стандарты клиентского сервиса','Сотрудник'],['course','Продукты, услуги и клиентский путь','Сотрудник'],['task','Наблюдать за диалогом наставника','Сотрудник'],['task','Провести диалог под наблюдением','Сотрудник'],['test','Проверка стандартов общения','Сотрудник'],['checkpoint','Защитить рабочий кейс','Наставник'],['meeting','Разобрать ошибки диалога','Наставник'],['task','Повторить практический кейс','Сотрудник']]},
  {id:'warehouse',name:'Склад',condition:'Подразделение = складская логистика',success:'Практический навык подтверждён',items:[['course','Охрана труда и складские операции','Сотрудник'],['course','Приёмка, хранение и инвентаризация','Сотрудник'],['course','Работа в WMS и со сканером','Сотрудник'],['task','Выполнить смену с наставником','Сотрудник'],['checkpoint','Подтвердить безопасную операцию','Проверяющий'],['task','Самостоятельно собрать заказ','Сотрудник'],['course','Повторить безопасную операцию','Сотрудник'],['meeting','Разбор ошибки с наставником','Наставник']]},
  {id:'delivery',name:'Доставка',condition:'Должность = курьер / водитель',success:'Маршрут и приложение освоены',items:[['course','Маршрут, приложение и стандарты доставки','Сотрудник'],['article','Документы и правила передачи отправления','Сотрудник'],['task','Разобрать маршрут с наставником','Наставник'],['task','Выполнить первый маршрут','Сотрудник'],['test','Проверка работы в приложении','Сотрудник'],['checkpoint','Подтвердить качество первой доставки','Наставник'],['meeting','Разобрать ошибки маршрута','Наставник'],['task','Выполнить корректирующий маршрут','Сотрудник']]}
]});

processes.transfer=buildRich({title:'Внутренний переход',result:'Готовность к новой должности',event:'Мастер-система · должность изменилась',stages:7,start:'Должность изменилась',source:'Мастер-система',decision:'Какой тип перехода?',common:[
  ['checkpoint','Сопоставить навыки новой роли','Система'],['meeting','Обсудить ожидания и ответственность','Руководитель'],['goal','Сотруднику создать цели перехода','Сотрудник'],['task','Передать задачи предыдущей роли','Сотрудник']],checkpoint:'КТ готовности к новой роли',checkOwner:'Руководитель',post:[['survey','Собрать обратную связь 360','Коллеги'],['goal','Руководителю подтвердить цели на период','Руководитель'],['task','Скорректировать ИПР, сроки и поддержку','Сотрудник']],end:'Самостоятельно работает в новой роли',branches:[
  {id:'expert',name:'Экспертная роль',condition:'Тип перехода = рост экспертизы',items:[['course','Обязательная экспертиза новой роли','Сотрудник'],['article','Регламенты и карта ответственности','Сотрудник'],['task','Разобрать эталонный рабочий кейс','Наставник'],['task','Выполнить собственный кейс','Сотрудник'],['checkpoint','Защитить кейс у эксперта','Эксперт'],['goal','Зафиксировать результат экспертизы','Сотрудник'],['course','Закрыть выявленный пробел','Сотрудник'],['meeting','Разбор кейса и новая попытка','Эксперт']]},
  {id:'manager',name:'Переход в руководство',condition:'Новая роль управляет командой',items:[['course','Роль руководителя и лидерство','Сотрудник'],['course','SMART цели и регулярный менеджмент','Сотрудник'],['task','Составить карту команды','Сотрудник'],['meeting','Провести первую встречу 1:1','Сотрудник'],['checkpoint','Оценить качество управленческой практики','Руководитель'],['survey','Получить обратную связь команды','Команда'],['meeting','Подготовиться с наставником','Наставник'],['task','Повторить управленческий цикл','Сотрудник']]},
  {id:'career',name:'Смена направления',condition:'Семейство должностей изменилось',items:[['checkpoint','Оценить переносимые навыки','Руководитель'],['goal','Сотруднику собрать ИПР под роль','Сотрудник'],['course','Освоить базовые знания функции','Сотрудник'],['task','Пройти job shadowing','Сотрудник'],['task','Выполнить практику в новой функции','Сотрудник'],['checkpoint','Подтвердить результат практики','Эксперт'],['course','Добавить базовый модуль в ИПР','Сотрудник'],['meeting','Уточнить ИПР с руководителем','Руководитель']]}
]});

processes.learning=buildRich({title:'Программа обучения',result:'Пробел навыка закрыт и подтверждён',event:'Оценка, расписание или ручной запуск',stages:7,start:'Потребность в обучении найдена',source:'Оценка / руководитель',decision:'Почему назначено обучение?',common:[
  ['checkpoint','Определить навык и требуемый уровень','Система'],['test','Провести входную диагностику','Сотрудник'],['task','Сформировать назначение и срок обучения','Система'],['task','Руководителю подтвердить критерий применения','Руководитель']],checkpoint:'Проверка применения навыка',checkOwner:'Руководитель',post:[['task','Зафиксировать рабочий результат','Сотрудник'],['survey','Оценить полезность программы','Сотрудник'],['task','Продлить маршрут и подключить руководителя','Система']],end:'Целевой уровень навыка подтверждён',branches:[
  {id:'gap',name:'Пробел по оценке',condition:'Оценка навыка ниже целевого уровня',success:'Уровень навыка достигнут',items:[['course','Персональная программа по пробелу','Сотрудник'],['article','Материалы из Базы знаний LMS','Сотрудник'],['task','Разобрать пример с наставником','Наставник'],['task','Применить навык в рабочем кейсе','Сотрудник'],['test','Повторная оценка навыка','Сотрудник'],['checkpoint','Подтвердить перенос в работу','Руководитель'],['course','Добавить материал по ошибкам','Сотрудник'],['task','Назначить дополнительную практику','Руководитель']]},
  {id:'mandatory',name:'Обязательная программа',condition:'Должность требует обучения или допуска',success:'Тест пройден и допуск оформлен',items:[['article','Регламент и обязательные требования','Сотрудник'],['course','Обязательная учебная программа','Сотрудник'],['test','Проверка знаний','Сотрудник'],['task','Выполнить обязательную практику','Сотрудник'],['checkpoint','Провести аттестацию','Проверяющий'],['task','Оформить допуск','Ответственный'],['course','Повторить обязательный модуль','Сотрудник'],['meeting','Разобрать ошибки перед пересдачей','Наставник']]},
  {id:'request',name:'Обучение по запросу',condition:'Инициатор = сотрудник или руководитель',success:'Применение подтверждено руководителем',items:[['article','Подборка статей и видео','Сотрудник'],['course','Курс по выбранной теме','Сотрудник'],['meeting','Вебинар или практический тренинг','Эксперт'],['task','Выполнить рабочую практику','Сотрудник'],['meeting','Обсудить применение с руководителем','Руководитель'],['task','Зафиксировать пример применения навыка','Сотрудник'],['task','Уточнить запрос и заменить материал','Сотрудник'],['meeting','Подобрать другую практику','Руководитель']]}
]});

const queryParams=new URLSearchParams(location.search),draftName=queryParams.get('name')||'Новый процесс',draftResult=queryParams.get('result')||'Целевой результат процесса',draftEvent=queryParams.get('event')||'Мастер-система · сотрудник вышел';
const draftBranches=[['branch1','Клиентский офис','Подразделение = клиентские офисы','#e6f7f1'],['branch2','Склад','Подразделение = складская логистика','#fff2d8'],['branch3','Доставка','Должность = курьер / водитель','#eeeaff']];
processes.draft={title:draftName,result:draftResult,event:draftEvent,meta:'Пустой процесс · 3 ветки · 0 действий',branches:draftBranches.map(x=>[x[0],x[1]]),frames:draftBranches.map((x,i)=>({id:x[0],title:x[1],condition:x[2],x:1240,y:[20,500,980][i],w:2820,h:420,color:x[3]})),nodes:[N('s','start',draftEvent,60,690,'Система'),N('d','decision','Какая ветка подходит?',1045,520,'Система')],edges:[E('s','d','Рассчитать условия')]};
processes.aiDraft=JSON.parse(JSON.stringify(processes.onboarding));processes.aiDraft.title=draftName;processes.aiDraft.result=draftResult;processes.aiDraft.event=draftEvent;processes.aiDraft.meta='AI черновик · 8 этапов · 3 ветки · 47 действий';processes.aiDraft.nodes.find(x=>x.id==='s').title=draftEvent;
const requestedProcess=queryParams.get('process');
const state={key:processes[requestedProcess]?requestedProcess:'onboarding',scale:.58,tx:34,ty:50,mode:'edit',selected:null,tool:'select',testBranch:'client',testOutcome:'success',drag:null,connectFrom:null,catalogType:'course',catalogMode:'add',edgeIndex:null};
state.testBranch=processes[state.key].branches[0][0];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const els={viewport:$('#viewport'),world:$('#world'),nodes:$('#nodes'),frames:$('#frames'),svg:$('#connections'),edgeActions:$('#edgeActions'),title:$('#processTitle'),result:$('#processResult'),meta:$('#processMeta'),picker:$('#pickerMenu'),inspector:$('#inspector'),test:$('#testPanel'),toast:$('#toast')};

function renderPicker(){els.picker.innerHTML=Object.entries(processes).map(([k,p])=>`<button data-process="${k}" class="${k===state.key?'active':''}"><b>${p.title}</b><small>${p.result} · ${p.nodes.length} элементов</small></button>`).join('');$$('[data-process]').forEach(b=>b.onclick=()=>{state.key=b.dataset.process;state.selected=null;els.picker.classList.remove('open');render();fit(true);});}
function render(){const p=processes[state.key];els.title.textContent=p.title;els.result.textContent=p.result;els.meta.textContent=p.meta;$('#aiProcess').textContent=state.key==='draft'?'✦ Собрать процесс с AI':'✦ Дополнить с AI';renderPicker();renderFrames(p);renderBranches(p);renderNodes(p);renderEdges(p);renderSettings(p);applyTransform();closeInspector();if(state.mode==='test')runTest();}
function renderSettings(p){$('#settingEvent').textContent=p.event||'Системное или ручное событие';$('#settingBranches').innerHTML=p.frames.map(f=>`<div class="setting-branch"><b>${f.title}</b><span>${f.condition}</span><span>Роли: ${[...new Set(p.nodes.filter(n=>n.branch===f.id).map(n=>n.owner))].join(', ')}</span></div>`).join('');}
function renderFrames(p){els.frames.innerHTML=p.frames.map(f=>{const branchNodes=p.nodes.filter(n=>n.branch===f.id),roles=[...new Set(branchNodes.map(n=>n.owner))].slice(0,3).join(' · ');return `<section class="branch-frame ${branchNodes.length?'':'empty'}" style="left:${f.x}px;top:${f.y}px;width:${f.w}px;height:${f.h}px;--frame:${f.color}"><div class="branch-head"><b>${f.title}</b><span>${f.condition}</span><span>${roles?'Роли: '+roles:'Роли задаются при добавлении действий'}</span><button class="branch-ai" data-branch-ai="${f.id}">✦ Собрать ветку с AI</button></div></section>`}).join('');$$('[data-branch-ai]').forEach(b=>b.onclick=e=>{e.stopPropagation();openBranchAI(b.dataset.branchAi);});}
function nodeHTML(n){const dim=isDim(n)?' dim':'';const hi=!dim&&state.mode==='test'?' highlight':'';return `<article class="node ${n.type}${dim}${hi}" data-id="${n.id}" style="left:${n.x}px;top:${n.y}px;--node:${C[n.type]||C.task}"><span class="port in"></span><div class="node-body"><div class="node-type"><b>${icon[n.type]||'•'}</b>${typeName[n.type]||n.type}</div><div class="node-title">${n.title}</div></div><footer class="node-foot"><span title="Исполнитель и шаблон уведомления">🔔 ${n.owner}</span><b>${n.time}</b></footer><span class="port out"></span></article>`;}
function renderNodes(p){els.nodes.innerHTML=p.nodes.map(nodeHTML).join('');$$('.node').forEach(el=>{el.onpointerdown=startNodeDrag;el.classList.toggle('connection-source',state.connectFrom===el.dataset.id);const port=el.querySelector('.port.out');port.onpointerdown=e=>e.stopPropagation();port.onclick=e=>{e.stopPropagation();startConnect(el.dataset.id)};el.onclick=e=>{if(state.drag?.moved)return;e.stopPropagation();if(state.connectFrom&&state.connectFrom!==el.dataset.id){p.edges.push(E(state.connectFrom,el.dataset.id,'Новый переход'));state.connectFrom=null;els.viewport.classList.remove('connecting');renderNodes(p);renderEdges(p);toast('Переход создан. Нажмите + на стрелке, чтобы вставить действие.');return}selectNode(el.dataset.id);};});}
function defs(){return `<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#8aa3b8"/></marker></defs>`;}
function edgePath(a,b){const aw=a.type==='decision'?144:(a.type==='start'||a.type==='end'?152:216);const ah=a.type==='decision'?144:(a.type==='start'||a.type==='end'?78:112);const bh=b.type==='decision'?144:(b.type==='start'||b.type==='end'?78:112);const x1=a.x+aw,y1=a.y+ah/2,x2=b.x,y2=b.y+bh/2;if(x2>x1+40){const m=(x1+x2)/2;return `M${x1},${y1} C${m},${y1} ${m},${y2} ${x2},${y2}`;}const loop=Math.max(x1,x2)+80;return `M${x1},${y1} C${loop},${y1} ${loop},${y2+95} ${x2},${y2}`;}
function renderEdges(p){const map=Object.fromEntries(p.nodes.map(n=>[n.id,n]));let s=defs();p.edges.forEach((e,i)=>{const a=map[e.from],b=map[e.to];if(!a||!b)return;const dim=isEdgeDim(e)?' dim':'';const d=edgePath(a,b);s+=`<path class="${e.tone||''}${dim}" d="${d}" data-edge="${i}"/>`;if(e.label){const x=(a.x+(a.type==='decision'?144:216)+b.x)/2,y=(a.y+b.y)/2+55;const w=Math.max(70,e.label.length*6.2+18);s+=`<g class="edge-label${dim}"><rect x="${x-w/2}" y="${y-13}" width="${w}" height="26"></rect><text x="${x}" y="${y}">${e.label}</text></g>`;}});els.svg.innerHTML=s;renderEdgeActions(p,map);}
function renderEdgeActions(p,map){els.edgeActions.innerHTML=p.edges.map((e,i)=>{const a=map[e.from],b=map[e.to];if(!a||!b||isEdgeDim(e))return'';const aw=a.type==='decision'?144:(a.type==='start'||a.type==='end'?152:216),ah=a.type==='decision'?144:(a.type==='start'||a.type==='end'?78:112),bh=b.type==='decision'?144:(b.type==='start'||b.type==='end'?78:112);const x=(a.x+aw+b.x)/2,y=(a.y+ah/2+b.y+bh/2)/2;return `<button class="edge-add" style="left:${x}px;top:${y}px" data-edge-add="${i}" title="Добавить действие в этот переход">+</button>`}).join('');$$('[data-edge-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();state.edgeIndex=+b.dataset.edgeAdd;openCatalog('task','edge')});}
function startConnect(id){state.connectFrom=id;els.viewport.classList.add('connecting');renderNodes(processes[state.key]);toast('Выберите карточку, куда должен вести переход. Esc — отменить.');}
function isDim(n){if(state.mode!=='test')return false;if(n.branch!=='common'&&n.branch!==state.testBranch)return true;if(!n.outcomes.includes(state.testOutcome))return true;return false;}
function isEdgeDim(e){if(state.mode!=='test')return false;if(e.branch!=='common'&&e.branch!==state.testBranch)return true;if(e.outcome!=='any'&&e.outcome!==state.testOutcome)return true;return false;}
function renderBranches(p){const sel=$('#testBranch');sel.innerHTML=p.branches.map(([id,name])=>`<option value="${id}" ${state.testBranch===id?'selected':''}>${name}</option>`).join('');if(!p.branches.some(x=>x[0]===state.testBranch))state.testBranch=p.branches[0][0];}
function selectNode(id){
  state.selected=id;$$('.node').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));
  const n=processes[state.key].nodes.find(x=>x.id===id);if(!n)return;
  const selectable=!!catalogs[n.type],source=n.catalogMeta||catalogNames[n.type]||'Объект процесса',objectId=n.catalogId||`${n.type}-${String(Math.abs(hashCode(n.title))).slice(0,4)}`;
  els.inspector.innerHTML=`<header><button data-close-inspector>×</button><small>${typeName[n.type]}</small><h3>${n.title}</h3></header>
    ${selectable?`<section><b>Объект из библиотеки</b><div class="object-link" style="margin-top:9px"><i>${icon[n.type]||'▣'}</i><span><b>${n.title}</b><small>${source} · ID ${objectId}</small></span><button id="replaceObject">Заменить</button></div></section>`:''}
    <section><label>Название размещения<input id="nodeTitleInput" value="${n.title}"></label><label>Исполнитель<select><option selected>${n.owner}</option><option>Сотрудник</option><option>Руководитель</option><option>Наставник</option><option>HR</option><option>Система</option></select></label><label>Когда создаётся<select><option>${n.time}</option><option>С открытием этапа</option><option>После предыдущего результата</option><option>За 3 дня до контрольной точки</option></select></label></section>
    <section><label>Шаблон уведомления · опционально<select><option>${n.notification}</option><option>Не отправлять</option><option>Назначено новое действие</option><option>Напомнить о сроке</option><option>Результат требует внимания</option></select></label><div class="explain">Уведомление привязано к событию этого действия. Получатели берутся из роли исполнителя и участников процесса.</div></section>
    <section><b>Что происходит дальше</b><div class="output-list">${outgoingFor(n.id).map(e=>`<div class="output ${e.tone||''}"><i>${e.tone==='negative'?'↻':'→'}</i><span>${e.label||'Перейти к следующему действию'}</span></div>`).join('')||'<div class="output"><span>Завершает маршрут</span></div>'}</div><button class="btn secondary" id="connectAction" style="width:100%;margin-top:10px">+ Добавить переход</button></section>`;
  els.inspector.classList.add('open');els.inspector.setAttribute('aria-hidden','false');$('[data-close-inspector]').onclick=closeInspector;$('#nodeTitleInput').onchange=e=>{n.title=e.target.value;renderNodes(processes[state.key]);renderEdges(processes[state.key]);};if($('#replaceObject'))$('#replaceObject').onclick=()=>openCatalog(n.type,'replace');$('#connectAction').onclick=()=>{closeInspector();startConnect(n.id)};
}
function hashCode(s){return [...s].reduce((a,c)=>((a<<5)-a)+c.charCodeAt(0),0)}
function outgoingFor(id){return processes[state.key].edges.filter(e=>e.from===id);}
function closeInspector(){els.inspector.classList.remove('open');els.inspector.setAttribute('aria-hidden','true');state.selected=null;}
function applyTransform(){els.world.style.transform=`translate(${state.tx}px,${state.ty}px) scale(${state.scale})`;$('#zoomValue').textContent=Math.round(state.scale*100)+'%';}
function fit(comfortable=false){const w=els.viewport.clientWidth,h=els.viewport.clientHeight,natural=Math.min(.78,(w-70)/5200,(h-70)/1500);state.scale=comfortable?Math.max(.48,Math.min(.60,natural*1.9)):natural;state.tx=comfortable?30:Math.max(28,(w-5200*state.scale)/2);state.ty=comfortable?36:Math.max(30,(h-1500*state.scale)/2);applyTransform();}
function setZoom(z,cx=els.viewport.clientWidth/2,cy=els.viewport.clientHeight/2){const old=state.scale;state.scale=Math.max(.35,Math.min(1.35,z));state.tx=cx-(cx-state.tx)*(state.scale/old);state.ty=cy-(cy-state.ty)*(state.scale/old);applyTransform();}
function startNodeDrag(e){if(state.mode!=='edit'||state.tool!=='select')return;const el=e.currentTarget,n=processes[state.key].nodes.find(x=>x.id===el.dataset.id);state.drag={kind:'node',n,sx:e.clientX,sy:e.clientY,ox:n.x,oy:n.y,moved:false};el.setPointerCapture(e.pointerId);}
window.addEventListener('pointermove',e=>{if(!state.drag)return;if(Math.abs(e.clientX-state.drag.sx)+Math.abs(e.clientY-state.drag.sy)>4)state.drag.moved=true;if(state.drag.kind==='node'){state.drag.n.x=Math.round(state.drag.ox+(e.clientX-state.drag.sx)/state.scale);state.drag.n.y=Math.round(state.drag.oy+(e.clientY-state.drag.sy)/state.scale);const el=$(`[data-id="${state.drag.n.id}"]`);el.style.left=state.drag.n.x+'px';el.style.top=state.drag.n.y+'px';renderEdges(processes[state.key]);}else{state.tx=state.drag.ox+(e.clientX-state.drag.sx);state.ty=state.drag.oy+(e.clientY-state.drag.sy);applyTransform();}});
window.addEventListener('pointerup',()=>{setTimeout(()=>state.drag=null,0);els.viewport.classList.remove('dragging');});
els.viewport.onpointerdown=e=>{if(e.target!==els.viewport&&e.target!==els.world&&e.target!==els.svg)return;if(state.tool==='hand'||e.target===els.viewport||e.target===els.world||e.target===els.svg){state.drag={kind:'pan',sx:e.clientX,sy:e.clientY,ox:state.tx,oy:state.ty,moved:false};els.viewport.classList.add('dragging');closeInspector();}};
els.viewport.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey){setZoom(state.scale*(e.deltaY>0?.92:1.08),e.clientX,e.clientY);}else{state.tx-=e.shiftKey?e.deltaY:e.deltaX;state.tx-=e.shiftKey?0:e.deltaY;state.ty-=e.deltaX?0:e.deltaY*.15;applyTransform();}},{passive:false});

function setMode(mode){state.mode=mode;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));els.test.classList.toggle('open',mode==='test');els.test.setAttribute('aria-hidden',mode!=='test');$('#settingsPanel').classList.toggle('open',mode==='settings');$('#settingsPanel').setAttribute('aria-hidden',mode!=='settings');closeInspector();renderNodes(processes[state.key]);renderEdges(processes[state.key]);if(mode==='test')runTest();}
function runTest(){state.testBranch=$('#testBranch').value;state.testOutcome=$('#testOutcome').value;renderNodes(processes[state.key]);renderEdges(processes[state.key]);const p=processes[state.key],name=p.branches.find(x=>x[0]===state.testBranch)?.[1];const count=p.nodes.filter(n=>!isDim(n)).length;$('#testSummary').innerHTML=`<b>${count} действий войдут в маршрут.</b><br>${name}. ${state.testOutcome==='success'?'Основной путь до результата.':'Показан возврат на корректирующее действие и повторная контрольная точка.'}`;}
function openBranchAI(branch){const p=processes[state.key],frame=p.frames.find(f=>f.id===branch);els.inspector.innerHTML=`<header><button data-close-inspector>×</button><small>AI подбор</small><h3>${frame.title}</h3></header><section><div class="explain">AI учитывает условие ветки «${frame.condition}», целевой результат процесса и уже добавленные действия.</div></section><section><b>Предлагает добавить</b><div class="output-list" style="margin-top:10px"><label class="output"><input type="checkbox" checked> Курс или материал из каталогов</label><label class="output"><input type="checkbox" checked> Практическая задача с проверкой</label><label class="output"><input type="checkbox" checked> Контрольная точка с руководителем</label></div><button class="btn primary" id="addSuggestions" style="width:100%;margin-top:14px">Добавить 3 элемента</button></section>`;els.inspector.classList.add('open');$('[data-close-inspector]').onclick=closeInspector;$('#addSuggestions').onclick=()=>{const existing=p.nodes.filter(n=>n.branch===branch),baseX=frame.x+60,baseY=frame.y+110,items=[['course','Стандарты и знания для роли','Сотрудник'],['task','Практическая задача по роли','Сотрудник'],['checkpoint','Подтвердить результат практики','Руководитель']],ids=[];items.forEach((it,i)=>{const id='ai'+Date.now()+i,n=N(id,it[0],it[1],baseX+(existing.length+i)*270,baseY,it[2],branch);n.catalogId=`ai-${i+1}`;n.catalogMeta=catalogNames[it[0]];p.nodes.push(n);ids.push(id)});if(existing.length){p.edges.push(E(existing.at(-1).id,ids[0],'AI дополнение',branch))}else{p.edges.push(E('d',ids[0],frame.title,branch))}p.edges.push(E(ids[0],ids[1]),E(ids[1],ids[2]));render();toast('AI добавил связанные объекты в ветку. Проверьте их перед публикацией.');closeInspector();};}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2600);}
function openCatalog(type='course',mode='add'){state.catalogType=catalogs[type]?type:'task';state.catalogMode=mode;$('#catalogTitle').textContent=mode==='replace'?'Замените объект':mode==='edge'?'Добавьте действие в переход':'Добавьте объект в процесс';$('#catalogSearch').value='';renderCatalog();$('#catalogModal').classList.add('open');$('#catalogModal').setAttribute('aria-hidden','false');$('#addMenu').classList.remove('open');}
function renderCatalog(){const types=Object.keys(catalogs);$('#catalogTypes').innerHTML=types.map(t=>`<button class="${t===state.catalogType?'active':''}" data-catalog-type="${t}"><span>${catalogNames[t]}</span><small>${catalogs[t].length}</small></button>`).join('');const q=$('#catalogSearch').value.toLowerCase();const items=catalogs[state.catalogType].filter(x=>(x[0]+x[1]+x[2]).toLowerCase().includes(q));$('#catalogList').innerHTML=items.map(x=>`<article class="catalog-item"><span class="catalog-icon">${icon[state.catalogType]||'▣'}</span><span><b>${x[1]}</b><small>${x[2]} · ID ${x[0]} · Опубликовано</small></span><button class="btn" data-pick-object="${x[0]}">${state.catalogMode==='replace'?'Выбрать':'Добавить'}</button></article>`).join('')||'<div class="settings-note">Ничего не найдено</div>';$$('[data-catalog-type]').forEach(b=>b.onclick=()=>{state.catalogType=b.dataset.catalogType;renderCatalog()});$$('[data-pick-object]').forEach(b=>b.onclick=()=>pickCatalogObject(b.dataset.pickObject));}
function pickCatalogObject(id){const item=catalogs[state.catalogType].find(x=>x[0]===id);if(!item)return;const p=processes[state.key];if(state.catalogMode==='replace'&&state.selected){const n=p.nodes.find(x=>x.id===state.selected);n.type=state.catalogType;n.title=item[1];n.catalogId=item[0];n.catalogMeta=item[2];renderNodes(p);renderEdges(p);selectNode(n.id);toast('Объект заменён, настройки размещения сохранены.');}
  else if(state.catalogMode==='edge'&&p.edges[state.edgeIndex]){const edge=p.edges[state.edgeIndex],a=p.nodes.find(x=>x.id===edge.from),b=p.nodes.find(x=>x.id===edge.to),nid='new'+Date.now();const n=N(nid,state.catalogType,item[1],Math.round((a.x+b.x)/2),Math.round((a.y+b.y)/2+85),'Сотрудник',edge.branch);n.catalogId=item[0];n.catalogMeta=item[2];p.nodes.push(n);p.edges.splice(state.edgeIndex,1,E(edge.from,nid,edge.label,edge.branch,edge.outcome,edge.tone),E(nid,edge.to,'',edge.branch,edge.outcome,edge.tone));renderNodes(p);renderEdges(p);selectNode(nid);toast('Действие добавлено в переход.');}
  else{addNodeFromCatalog(state.catalogType,item)}closeCatalog();}
function addNodeFromCatalog(type,item){const p=processes[state.key],id='new'+Date.now(),n=N(id,type,item[1],Math.round((els.viewport.clientWidth/2-state.tx)/state.scale),Math.round((els.viewport.clientHeight/2-state.ty)/state.scale),'Сотрудник');n.catalogId=item[0];n.catalogMeta=item[2];p.nodes.push(n);renderNodes(p);renderEdges(p);selectNode(id);toast('Объект добавлен. Соедините его с маршрутом через порт +.');}
function closeCatalog(){$('#catalogModal').classList.remove('open');$('#catalogModal').setAttribute('aria-hidden','true');state.edgeIndex=null;}
function openWizard(){const p=processes[state.key],empty=state.key==='draft';wizardStep=2;$('#aiModal h2').textContent=empty?'Собрать процесс с AI':'Дополнить текущий процесс с AI';$('#aiModal header p').textContent=empty?'AI соберёт этапы, подберёт объекты из каталогов и создаст переходы внутри уже заданных веток.':'AI учитывает текущие ветки, условия, роли и уже добавленные действия. Выберите, где найти пробелы.';$('.branch-cards').innerHTML=p.frames.map(f=>`<label><input type="checkbox" checked><span><b>${f.title}</b><small>${f.condition}</small></span></label>`).join('');$('.source-check').innerHTML=`<input type="checkbox" checked> ${empty?'Подобрать курсы, статьи, тесты, опросы, задачи и контрольные точки из доступных библиотек':'Найти пропуски в последовательности, подобрать элементы из каталога и предложить переходы по результатам'}`;syncWizard();$('#aiModal').classList.add('open');$('#aiModal').setAttribute('aria-hidden','false');}
let wizardStep=1;function syncWizard(){$$('.wizard-body').forEach(x=>x.classList.toggle('hidden',+x.dataset.step!==wizardStep));$$('.wizard-steps span').forEach((x,i)=>x.classList.toggle('active',i+1===wizardStep));$('#wizardNext').textContent=wizardStep===3?'Создать процесс':'Продолжить';}
function createAIProcess(){const p=JSON.parse(JSON.stringify(processes.learning));p.title=$('#aiName').value||'Новый процесс';p.result=$('#aiGoal').value||'Целевой результат достигнут';p.meta='AI черновик · 6 этапов · 3 ветки · 22 элемента';const titles={s:'Назначен руководителем',profile:'Определить целевые управленческие навыки',approve:'Подтвердить критерии успешности',goal:'Создать цель развития руководителя',d:'Какой профиль руководителя?',g1:'Первые 90 дней руководителя',g2:'Провести 1:1 под наблюдением',g3:'Разобрать управленческую ситуацию',gfix:'Разбор кейса с наставником',m1:'Диагностика управленческих практик',m2:'Сформировать цель по команде',m3:'Получить обратную связь 360',mfix:'Коуч-сессия по зоне риска',r1:'Материалы по делегированию',r2:'Практика делегирования',r3:'Обсудить результат с руководителем',rfix:'Уточнить пробел и заменить практику',kt:'КТ: управление по стандартам',practice:'Зафиксировать результат команды',feedback:'Пульс команды',correct:'Скорректировать ИПР руководителя',end:'Самостоятельно управляет командой'};const specs={gfix:['meeting','Наставник'],m1:['checkpoint','Система'],m2:['goal','Руководитель'],m3:['survey','Команда'],mfix:['meeting','Наставник'],r2:['task','Сотрудник']};p.nodes.forEach(n=>{if(titles[n.id])n.title=titles[n.id];if(specs[n.id]){n.type=specs[n.id][0];n.owner=specs[n.id][1]}});p.frames[0].title='Новый руководитель';p.frames[0].condition='Опыт управления: нет';p.frames[1].title='Опытный руководитель';p.frames[1].condition='Опыт управления: есть';p.frames[2].title='Пробел people management';p.frames[2].condition='Оценка ниже 70%';p.branches=[['gap','Новый руководитель'],['mandatory','Опытный руководитель'],['request','Пробел people management']];processes.ai=p;state.key='ai';state.testBranch='gap';state.mode='edit';$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='edit'));els.test.classList.remove('open');els.test.setAttribute('aria-hidden','true');$('#aiModal').classList.remove('open');render();fit(true);toast('AI собрал черновик. Проверьте ветки, переходы и назначения.');}

$('#processPicker').onclick=e=>{e.stopPropagation();els.picker.classList.toggle('open');};document.addEventListener('click',e=>{if(!e.target.closest('.process-head'))els.picker.classList.remove('open');if(!e.target.closest('.add-menu')&&!e.target.closest('#addTool'))$('#addMenu').classList.remove('open');});
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('.tool[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;$$('.tool[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});$('#addTool').onclick=e=>{e.stopPropagation();$('#addMenu').classList.toggle('open');};$$('[data-add]').forEach(b=>b.onclick=()=>openCatalog(b.dataset.add,'add'));$('#commentTool').onclick=()=>toast('Кликните на объект, чтобы оставить комментарий участникам настройки.');
$('#zoomIn').onclick=()=>setZoom(state.scale+.1);$('#zoomOut').onclick=()=>setZoom(state.scale-.1);$('#fitView').onclick=()=>fit(false);$('#testBranch').onchange=runTest;$('#testOutcome').onchange=runTest;$('#runTest').onclick=runTest;$('#aiProcess').onclick=openWizard;$('#editSettings').onclick=()=>toast('В прототипе условия показаны в режиме настройки. В продукте здесь откроется их редактор.');$$('[data-close]').forEach(b=>b.onclick=()=>$('#aiModal').classList.remove('open'));$('#wizardNext').onclick=()=>{if(wizardStep<3){wizardStep++;syncWizard();}else if(state.key==='draft'){queryParams.set('process','aiDraft');location.search=queryParams.toString();}else{$('#aiModal').classList.remove('open');toast('AI нашёл пробелы и подготовил предложения для текущих веток.');}};
$('#catalogSearch').oninput=renderCatalog;$('#catalogClose').onclick=closeCatalog;$('#catalogCancel').onclick=closeCatalog;$$('.catalog-chips button').forEach(b=>b.onclick=()=>{$$('.catalog-chips button').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});window.addEventListener('keydown',e=>{if(e.key==='Escape'){state.connectFrom=null;els.viewport.classList.remove('connecting');closeCatalog();renderNodes(processes[state.key]);}});
window.addEventListener('resize',()=>fit(true));render();setTimeout(()=>fit(true),0);
